export type Card = {
  abilities: string | null,
  artist: string,
  body_text: string,
  card_number: number,
  card_variants: string | null,
  classifications: string | null,
  color: string,
  cost: number,
  flavor_text: string,
  id: number,
  image_url: string,
  inkable: boolean,
  lore: string | null,
  move_cost: string | null,
  name: string,
  rarity: string,
  set_id: string,
  set_name: string,
  set_num: number,
  strength: string | null,
  type: string,
  willpower: string | null
}