services:
  # WEBAPP
  webapp:
    build:
      context: ../front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      ycardsmarket_network:
        aliases:
          - ycardsmarket-front.local

  # BACKEND
  back:
    build:
      context: ../back
      dockerfile: Dockerfile
    depends_on:
      - database
    restart: on-failure
    ports:
      - "1000:8000"
    networks:
      ycardsmarket_network:
        aliases:
          - ycardsmarket-back.local

  # DATABASE
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - /usr/local/postgresql/ycardsmarket:/var/lib/postgresql/data
    networks:
      ycardsmarket_network:
        aliases:
          - ycardsmarket-database.local

networks:
  ycardsmarket_network:
    driver: bridge