### GET BY ID
GET http://{{ url }}/api/v1/lorcana/200/seasons/1

### CREATE LORCANA COLLECTION (SECURED)
POST http://{{ url }}/api/v1/lorcana/collections
Content-Type: application/json
Authorization: Bearer {{ auth_jwt_token }}

{{
    // Set the token as a header
    request.addHeader("Authorization", "Bearer {{ YCARDSMARKET_JWT_TOKEN= }}");
}}

{
  "name": "Aggro/Control deck v1",
  "is_public": false
}

### GET BY ID (SECURED)
GET http://{{ url }}/api/v1/lorcana/collections/1
Authorization: Bearer {{ auth_jwt_token }}

### ADD LORCANA CARDS TO COLLECTION (SECURED)
POST http://{{ url }}/api/v1/lorcana/collections/1
Content-Type: application/json
Authorization: Bearer {{ auth_jwt_token }}

[1, 5, 20, 300]