### CREATE
POST http://{{ url }}/api/v1/users/register/
Content-Type: application/json

{
  "username": "test",
  "email": "test@email.com",
  "password": "testpass123",
  "password2": "testpass123",
  "bio": "Testing profile biography"
}

### LOGIN
POST http://{{ url }}/api/v1/users/auth/
Content-Type: application/json

{
  "username": "test",
  "password": "testpass123"
}

### GET PROFILE
GET http://{{ url }}/api/v1/users/profile/
Authorization: Bearer {{ auth_jwt_token }}